export const categories = [
    { value: "Amazing", label: "Amazing" },
    { value: "Historical", label: "Historical" },
    { value: "Ephemeral", label: "Ephemeral" },
    { value: "Random", label: "Random" },
    { value: "Sports", label: "Sports" },
    { value: "Scientific", label: "Scientific" },
    { value: "Personal", label: "Personal" },
    { value: "Numerical", label: "Numerical" },
    { value: "Movies", label: "Movies" },
    { value: "Comics", label: "Comics" },
    { value: "Media", label: "Media" },
    { value: "Pictures", label: "Pictures" },
    { value: "Sounds", label: "Sounds" },
    { value: "Links", label: "Links" },
    { value: "Multiples", label: "Multiples" },
    { value: "37th things", label: "37th things" },
];